### ISSUE TITLE
[Bug]: mission ran forever when workers larger than totalOps

### ISSUE THREAD

**Issue by kisscelia** [sine-io/cosbench-sineio#10]
```
<workstage name="get 4kb obs">
	  <work name="w-1" workers="50" totalOps="10" driver="driver1">
        <operation type="read" ratio="100" config="cprefix=test0;containers=c(2);oprefix=w1-4kib-;objects=s(1,10)" />
      </work>
	  
	  <work name="w-2" workers="50" totalOps="10" driver="driver2">
        <operation type="read" ratio="100" config="cprefix=test0;containers=c(2);oprefix=w2-4kib-;objects=s(1,10)" />
      </work>
    </workstage>
```

mission never end.

**Comment by kisscelia** [comment]
try to add validation.
![image](https://user-images.githubusercontent.com/13063673/191657283-4888b22f-7132-46ce-81ae-c32a81ef15cb.png)

**Comment by dongyzzzz** [comment]
When I use the "runtime" parameter, the system also says "Note: If use totalOps, workers should be less than or equal to totalOps!"

**Comment by kisscelia** [comment]
Hi, @dongyzzzz 
can you copy your xml to me?
Thank you.

**Comment by dongyzzzz** [comment]
<workflow>
    <workstage name="1Mwrite-0-0-400">
      <work name="main" **runtime**="100" workers="400">
        <operation config="cprefix=benchmarktest;containers=c(4);oprefix=1M;objects=s(1,10000000);sizes=c(1)MB" ratio="100" type="write"/>
      </work>
    </workstage>
  </workflow>

like so，I used "runtime" instead of "totalOps"

**Comment by kisscelia** [comment]
reopen this issue

**Comment by kisscelia** [comment]
fixed:
![image](https://github.com/sine-io/cosbench-sineio/assets/13063673/76d50c66-f480-4dbd-995f-c976ae3cacb3)

@dongyzzzz thank you.
