### ISSUE TITLE
Benchmark for s3 read with 4k files results high response time and low proc time

### ISSUE THREAD

**Issue by thenamehasbeentake** [sine-io/cosbench-sineio#39]
When benchmarking 4k s3 objects read,  we can find a big difference between response time and proc time.
The code is here.
https://github.com/sine-io/cosbench-sineio/blob/main/dev/cosbench-driver/src/com/intel/cosbench/driver/operator/Reader.java#L88-L95

`copyLarge(in, cout);` takes too long when object size is small.Maybe you can consider adjusting the implementation of this part.

**Comment by kisscelia** [comment]
Hi, @thenamehasbeentake 
can you paste your cosbench result and your xml  here?

It's my result for 4K Reading:
![image](https://github.com/sine-io/cosbench-sineio/assets/13063673/ecbe5c42-a7f4-4a9c-80fb-2446eec75bbb)
although the res time and proc time were so high, but it is the same between restime and proctime

**Comment by kisscelia** [comment]
> Cosbench result: ![image](https://private-user-images.githubusercontent.com/36036872/287573411-cf25974b-b55f-4e1a-a14b-d8d3bcf5ae56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTQxMjMsIm5iZiI6MTcwMTg1MzgyMywicGF0aCI6Ii8zNjAzNjg3Mi8yODc1NzM0MTEtY2YyNTk3NGItYjU1Zi00ZTFhLWExNGItZDhkM2JjZjVhZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODU1ZGU1MTk1ODlkYzYxMmE1Mzc4MjIxZDI5NDQ2ZmEwM2RjMmI5NGNlY2Q0YmFhNDk4ZTdjMjMxMDBhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hadkdgZZftr6c9lRqKYXXPvJYbo04G70DqCEEQbCIb0)
> 
> Xml example: [cosbench-xml.tar.gz](https://github.com/sine-io/cosbench-sineio/files/13541335/cosbench-xml.tar.gz)

may i ask a question?

driver1's IP is xx.xx.xx.131?
driver2's IP is xx.xx.xx.132?
...
driver10's IP is xx.xx.xx.140?

**Comment by kisscelia** [comment]
@thenamehasbeentake 
can you have a try, use driver1 to point to other node, maybe 132? 
the rule is  driver and service does not on the same machine.

**Comment by kisscelia** [comment]
you also can add my wechat account, please leave a comment, like "from github", i will know that.

thanks.

**Comment by kisscelia** [comment]
@thenamehasbeentake 
The important thing is you should change storage type to sio, when you want to use my version.

s3 is same to the intel version.
![image](https://github.com/sine-io/cosbench-sineio/assets/13063673/b7f7f929-0d88-4319-826e-78804fa1c54b)

**Comment by thenamehasbeentake** [comment]
> > Cosbench result: ![image](https://private-user-images.githubusercontent.com/36036872/287573411-cf25974b-b55f-4e1a-a14b-d8d3bcf5ae56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NTQxMjMsIm5iZiI6MTcwMTg1MzgyMywicGF0aCI6Ii8zNjAzNjg3Mi8yODc1NzM0MTEtY2YyNTk3NGItYjU1Zi00ZTFhLWExNGItZDhkM2JjZjVhZTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA5MTAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODU1ZGU1MTk1ODlkYzYxMmE1Mzc4MjIxZDI5NDQ2ZmEwM2RjMmI5NGNlY2Q0YmFhNDk4ZTdjMjMxMDBhYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hadkdgZZftr6c9lRqKYXXPvJYbo04G70DqCEEQbCIb0)
> > Xml example: [cosbench-xml.tar.gz](https://github.com/sine-io/cosbench-sineio/files/13541335/cosbench-xml.tar.gz)
> 
> may i ask a question?
> 
> driver1's IP is xx.xx.xx.131? driver2's IP is xx.xx.xx.132? ... driver10's IP is xx.xx.xx.140?

Of course.

**Comment by thenamehasbeentake** [comment]
> @thenamehasbeentake The important thing is you should change storage type to sio, when you want to use my version.
> 
> s3 is same to the intel version. ![image](https://private-user-images.githubusercontent.com/13063673/288356006-b7f7f929-0d88-4319-826e-78804fa1c54b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjczOTgsIm5iZiI6MTcwMTg2NzA5OCwicGF0aCI6Ii8xMzA2MzY3My8yODgzNTYwMDYtYjdmN2Y5MjktMGQ4OC00MzE5LTgyNmUtNzg4MDRmYTFjNTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDEyNTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzE3ZmZlNmVmYmU2YzY5NDcwMzAyYzdjY2M1YWE3NTNhMzMzOTJmODZjZDVmZjBkYzEyZDkxZDJlNDg2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.US5joVSPgpj3stWPCeP2_6tAdD-7t6IzDjtUyWYPX6g)

Thanks a lot. I will try to use it on the latest version when I have new storage servers.
Now we will close this issue first until the problem occurs again.
