### ISSUE TITLE
Not possible to run mixed workload of Range Read operations

### ISSUE THREAD

**Issue by ahmadrezaedalat** [sine-io/cosbench-sineio#6]
Currently it's not possible to run a mixed workload of two Range Read operations. 

For example the following work stage doesn't work. It is complaining that:  "cannot parse the xml configuration from <stream>, due to element "storage" occurs more than once. (parent class: com.intel.cosbench.config.Work)
 location: /work/work/work/work/storage "

<workstage name="4k and 256KB range reads- 1024 threads">
      <work name="main" type="normal" workers="1024" runtime="120" division="object">
        <storage type="s3" config="accesskey=QLFANDXA396MBSL7UOUN; secretkey=UTE9KFNw+h+rMZoblEvRN8yQT/6MoemelEuWdB1i; endpoint=https://192.168.0.139:10443; path_style_access=true; no_verify_ssl=true; is_range_request=true; file_length=4194304; chunk_length=4096"/>
        <operation type="read" ratio="50" config="containers=c(3); objects=r(1,3000000)" />
        <storage type="s3" config="accesskey=QLFANDXA396MBSL7UOUN; secretkey=UTE9KFNw+h+rMZoblEvRN8yQT/6MoemelEuWdB1i; endpoint=https://192.168.0.139:10443; path_style_access=true; no_verify_ssl=true; is_range_request=true; file_length=4194304; chunk_length=262144"/>
        <operation type="read" ratio="50" config="containers=c(3); objects=r(1,3000000)" />

      </work>
    </workstage>

**Comment by kisscelia** [comment]
Hi, @ahmadrezaedalat 
Can you share your xml config file?
I don't change the logic of the config module.

**Comment by kisscelia** [comment]
closed

@ahmadrezaedalat You can reopen it if needed
